server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
      routes:
        - id: my_route
          #uri: http://localhost:8001/
          uri: lb://my-load-balanced-service #用于负载均衡
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1

#负载均衡
my-load-balanced-service:
  ribbon:
    listOfServers: localhost:8001, localhost:8000
    #负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #可以判断服务是否可以ping通
    NFLoadBalancerPingClassName: gateway.controller.HealthExamination